AWSTemplateFormatVersion: 2010-09-09
Description: Deploys the EKS Cluster nodes for the capstone-welcome-app application.

Parameters:
  NodeRoleARN:
    Description: ARN of eks nodes IAM role.
    Type: String
    Default: "arn:aws:iam::928265084040:role/eks-node"

Resources:
  CapstoneWelcomeAppEKSNodeGroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: CapstoneWelcomeAppProd
      NodeRole: NodeRoleARN
      InstanceTypes: [ 't2.micro' ]
      ScalingConfig:
        MinSize: 1
        DesiredSize: 2
        MaxSize: 3
      Subnets:
        Fn::ImportValue:
          !Sub "${VPCStackName}-PrivateSubnetIds"
