AWSTemplateFormatVersion: 2010-09-09
Description: Deploys the EKS Cluster for the capstone-welcome-app application.

Parameters:
  VPCStackName:
    Description: Name of the stack used to configure the VPC.
    Type: String
    Default: capstone-welcome-app-eks-vpc

  PublicCIDR:
    Description: CIDR we want to allow access to the cluster endpoint.
    Type: String
    Default: 0.0.0.0/0

  ControlRoleARN:
    Description: ARN of control plane IAM role.
    Type: String
    Default: "arn:aws:iam::928265084040:role/eks-control"

Resources:
  # EKS Cluster for the Capstone Welcome App
  CapstoneWelcomeAppEKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: CapstoneWelcomeAppProd
      RoleArn: !Ref ControlRoleARN
      ResourcesVpcConfig:
        SecurityGroupIds:
          Fn::ImportValue:
            !Sub "${VPCStackName}-SecurityGroups"
        SubnetIds:
          Fn::ImportValue:
            !Sub "${VPCStackName}-SubnetIds"
        EndpointPublicAccess: true
        EndpointPrivateAccess: true
        PublicAccessCidrs:
          - !Ref PublicCIDR
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit
