AWSTemplateFormatVersion: 2010-09-09
Description: Deploys the EKS Cluster nodes for the capstone-welcome-app application.

Parameters:
  VPCStackName:
    Description: Name of the stack used to configure the VPC.
    Type: String
    Default: capstone-welcome-app-eks-vpc

  NodeRoleARN:
    Description: ARN of eks nodes IAM role.
    Type: String
    Default: "arn:aws:iam::928265084040:role/eks-node"

Resources:
  CapstoneWelcomeAppEKSNodeGroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: CapstoneWelcomeAppProd
      NodeRole: !Ref NodeRoleARN
      InstanceTypes: [ 't2.micro' ]
      ScalingConfig:
        MinSize: 1
        DesiredSize: 2
        MaxSize: 3
      Subnets:
        Fn::Split:
          - ","
          - Fn::ImportValue:
             !Sub "${VPCStackName}-PrivateSubnetIds"
