version: 2.1

# Use the kubernetes orb to facilitate controlling our cluster
orbs:
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  # lint: Lints the codebase using the tighten/duster Laravel lint tool. We
  # focus on the core Laravel Pint linting only.
  lint:
    docker:
      - image: cimg/php:8.2.8
    steps:
      - checkout
      - run:
          name: Install composer dependencies
          command: |
            composer install
      - run:
          name: Perform linting
          command: |
            ./vendor/bin/duster lint -u pint
  # build-image: Builds the Docker image and pushes to the registry
  build-image:
    docker:
      - image: cimg/aws:2023.07
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'Build docker image'
          command: |
            docker build -t capstone-welcome-app:build-${CIRCLE_WORKFLOW_ID:0:7} .
      - run:
          name: 'Login to AWS container registry'
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 928265084040.dkr.ecr.us-east-1.amazonaws.com
      - run:
          name: 'Tag image and push to registry'
          command: |
            docker tag capstone-welcome-app:build-${CIRCLE_WORKFLOW_ID:0:7} 928265084040.dkr.ecr.us-east-1.amazonaws.com/capstone-welcome-app:build-${CIRCLE_WORKFLOW_ID:0:7}
            docker push 928265084040.dkr.ecr.us-east-1.amazonaws.com/capstone-welcome-app:build-${CIRCLE_WORKFLOW_ID:0:7}
  # deploy: Ensures the eks cluster exists
  deploy:
    docker:
      - image: cimg/aws:2023.07
    steps:
      - checkout
      - run:
          name: 'Create / update EKS cluster from template'
          command: |
            aws cloudformation deploy \
              --stack-name capstone-welcome-app-eks-cluster \
              --template-file .circleci/cloudformation/eks-cluster.yml \
              --parameter-overrides PublicCIDR=$(curl -s http://checkip.amazonaws.com)/32
          # We increase the timeout for this step as during the first run when
          # infrastructure is being created this step will be slow, however in
          # normal runs where we don't change the cloudformation yaml we only
          # expect the PublicCIDR to change, which is a much smaller changeset
          # that should apply quite quickly.
          no_output_timeout: 30m

workflows:
  default:
    jobs:
      - lint
      - build-image:
          requires: [lint]
      - deploy:
          requires: [build-image]
