apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-welcome-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-welcome-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: capstone-welcome-app
    spec:
      containers:
        - name: capstone-welcome-app
          image: 928265084040.dkr.ecr.us-east-1.amazonaws.com/capstone-welcome-app:build-${CIRCLE_WORKFLOW_ID:0:7}
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: capstone-app-env
                  key: app-key
      imagePullSecrets:
        - name: capstone-registry-credentials
